"""Brief -> HTML email digest.

Per the manifesto's reuse-first note (CI-OS-Fable-build-goal-spec.md §7),
the Algolia-branded HTML template is reused here where a full report
html_path already exists (the collector/report renderer owns that
template); this module only wraps it (or a plain markdown body, for
ad-hoc/alert deliveries that have no pre-rendered file) in a minimal,
self-contained email-safe shell -- inline styles only, no external CSS,
since most mail clients strip <style> blocks or block remote assets.
"""

from __future__ import annotations

import html
import re

_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
_ITALIC_RE = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")
_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")

_SHELL = """\
<!DOCTYPE html>
<html>
  <body style="font-family: -apple-system, Helvetica, Arial, sans-serif; \
background:#f5f5f7; margin:0; padding:24px;">
    <div style="max-width:640px; margin:0 auto; background:#ffffff; \
border-radius:8px; padding:32px; color:#1d1d1f;">
      <h1 style="font-size:20px; margin:0 0 16px;">{title}</h1>
      <div style="font-size:14px; line-height:1.6;">{body}</div>
      {dashboard_link}
    </div>
  </body>
</html>
"""


def _markdown_body_to_html(markdown_text: str) -> str:
    escaped = html.escape(markdown_text, quote=False)

    def _link(match: "re.Match[str]") -> str:
        label, url = match.group(1), match.group(2)
        safe_url = html.escape(url, quote=True)
        return f'<a href="{safe_url}">{label}</a>'

    escaped = _LINK_RE.sub(_link, escaped)
    escaped = _BOLD_RE.sub(lambda m: f"<strong>{m.group(1)}</strong>", escaped)
    escaped = _ITALIC_RE.sub(lambda m: f"<em>{m.group(1)}</em>", escaped)
    paragraphs = [f"<p>{p}</p>" for p in escaped.split("\n\n") if p.strip()]
    return "\n".join(paragraphs)


def render_email_html(
    title: str,
    body_markdown: str | None = None,
    rendered_html_body: str | None = None,
    dashboard_url: str | None = None,
) -> str:
    """Render a self-contained HTML email digest.

    If `rendered_html_body` is given (an already-rendered report
    html_path's contents), it is embedded as-is (trusted -- generated by
    CI-OS's own report renderer, not raw user/adapter input). Otherwise
    `body_markdown` is escaped and lightly formatted.
    """
    if rendered_html_body is not None:
        body = rendered_html_body
    else:
        body = _markdown_body_to_html(body_markdown or "")

    dashboard_link = ""
    if dashboard_url:
        safe_url = html.escape(dashboard_url, quote=True)
        dashboard_link = (
            f'<p style="margin-top:24px;">'
            f'<a href="{safe_url}" style="color:#003dff;">View on the dashboard</a></p>'
        )

    return _SHELL.format(title=html.escape(title, quote=False), body=body, dashboard_link=dashboard_link)
